export const backup = [
  {
    siteId: 1,
    fieldCode: "AL01/13",
    siteName: "Kartitscher Sattel",
    latitude: "46,717889",
    longitude: "12,544111",
    country: "Austria",
    state: "Alps",
    settlement: "Kartitsch",
    mapGrid: "",
    siteDescription:
      "svahové slatiniště nad silnicí, mělké, nízkoproduktivní, hodně rašeliníků, ale i Carex dioica, Primula farinosa, méně zvodnělá plocha, bez stružek, bez tůněk",
    elevation: 1525,
    dateSampling: "8.7.2013",
    collector: "M. Horsák, V. Horsáková",
    plotSize: "",
    sampleSize: "",
    habitatSize: "",
    distanceForest: "",
    samplingMethod: "",
    waterPH: "6,2",
    waterConductivity: 189,
    lotNumber: "",
    releveNumber: 487777,
    dataType: "Fen",
    event: "",
    note: "",
  },
  {
    siteId: 2,
    fieldCode: "AL02/13",
    siteName: "Moso (Moos)",
    latitude: "46,666667",
    longitude: "12,398028",
    country: "Italy",
    state: "Alps",
    settlement: "Moso",
    mapGrid: "",
    siteDescription:
      "poměrně rozsáhlé bazické slatiniště se srážením pěnovce, hlavně v tůňkách, vlhké, vodnaté, hodně mechové, málo produktivní",
    elevation: 1536,
    dateSampling: "8.7.2013",
    collector: "M. Horsák, V. Horsáková",
    plotSize: "",
    sampleSize: "",
    habitatSize: 10000,
    distanceForest: "",
    samplingMethod: "",
    waterPH: "7,6",
    waterConductivity: 2150,
    lotNumber: "",
    releveNumber: 487778,
    dataType: "Fen",
    event: "",
    note: "",
  },
  {
    siteId: 3,
    fieldCode: "AL03/13",
    siteName: "Prameny Drávy",
    latitude: "46,722806",
    longitude: "12,253028",
    country: "Italy",
    state: "Alps",
    settlement: "",
    mapGrid: "",
    siteDescription:
      "bazické slatiniště s hnědými mechy pod turistickou cestou , silně zarůstá rákosem, ale stále hodně vlhké s bohatým mechovým patrem",
    elevation: 1190,
    dateSampling: "8.7.2013",
    collector: "M. Horsák, V. Horsáková",
    plotSize: "",
    sampleSize: "",
    habitatSize: 900,
    distanceForest: "",
    samplingMethod: "",
    waterPH: "7,9",
    waterConductivity: 792,
    lotNumber: "",
    releveNumber: 487779,
    dataType: "Fen",
    event: "",
    note: "",
  },
];
