export const backup = [
  /*   {
    siteId: 1,
    speciesName: "Nesovitrea hammonis",
    specification: "",
    live: 6,
    empty: 1,
    all: 7,
    lot: 2222,
    voucher: "",
    note: "",
  },
  {
    siteId: 1,
    speciesName: "Cochlicopa lubrica",
    specification: "",
    live: 1,
    empty: 0,
    all: 1,
    lot: 2222,
    voucher: "",
    note: "",
  },
  {
    siteId: 1,
    speciesName: "Vertigo substriata",
    specification: "",
    live: 5,
    empty: 1,
    all: 6,
    lot: 2222,
    voucher: "",
    note: "",
  },
  {
    siteId: 1,
    speciesName: "Radix labiata",
    specification: "cf.",
    live: 4,
    empty: 2,
    all: 6,
    lot: 2222,
    voucher: "",
    note: "",
  },
  {
    siteId: 1,
    speciesName: "Succinella oblonga",
    specification: "",
    live: 4,
    empty: 1,
    all: 5,
    lot: 2222,
    voucher: "",
    note: "",
  }, */
  /*   {
    siteId: 2,
    speciesName: "Vertigo genesii",
    specification: "",
    live: 32,
    empty: 32,
    all: 64,
    lot: "",
    voucher: 3,
    note: "",
  },
  {
    siteId: 2,
    speciesName: "Vallonia pulchella",
    specification: "",
    live: 28,
    empty: 9,
    all: 37,
    lot: "",
    voucher: "",
    note: "",
  },
  {
    siteId: 2,
    speciesName: "Nesovitrea hammonis",
    specification: "",
    live: 0,
    empty: 6,
    all: 6,
    lot: "",
    voucher: "",
    note: "",
  },
  {
    siteId: 2,
    speciesName: "Vertigo substriata",
    specification: "",
    live: 0,
    empty: 2,
    all: 2,
    lot: "",
    voucher: "",
    note: "",
  },
  {
    siteId: 2,
    speciesName: "Cochlicopa lubrica",
    specification: "",
    live: 0,
    empty: 2,
    all: 2,
    lot: "",
    voucher: "",
    note: "",
  },
  {
    siteId: 2,
    speciesName: "Oxyloma elegans",
    specification: "",
    live: 7,
    empty: 47,
    all: 54,
    lot: "",
    voucher: "",
    note: "",
  },
  {
    siteId: 2,
    speciesName: "Galba truncatula",
    specification: "",
    live: 3,
    empty: 2,
    all: 5,
    lot: "",
    voucher: "",
    note: "mladý jedinec",
  },
  {
    siteId: 2,
    speciesName: "Euconulus fulvus",
    specification: "",
    live: 1,
    empty: 4,
    all: 5,
    lot: "",
    voucher: "",
    note: "",
  }, */
  {
    siteId: 3,
    speciesName: "Vertigo geyeri",
    specification: "",
    live: 3,
    empty: 11,
    all: 14,
    lot: "",
    voucher: "",
    note: "",
  },
  {
    siteId: 3,
    speciesName: "Vertigo genesii",
    specification: "",
    live: 9,
    empty: 8,
    all: 17,
    lot: "",
    voucher: "",
    note: "",
  },
  {
    siteId: 3,
    speciesName: "Pupilla alpicola",
    specification: "",
    live: 3,
    empty: 7,
    all: 10,
    lot: "",
    voucher: "",
    note: "",
  },
  {
    siteId: 3,
    speciesName: "Vallonia pulchella",
    specification: "",
    live: 14,
    empty: 9,
    all: 23,
    lot: "",
    voucher: "",
    note: "",
  },
  {
    siteId: 3,
    speciesName: "Succinella oblonga",
    specification: "",
    live: 1,
    empty: 2,
    all: 3,
    lot: "",
    voucher: "",
    note: "",
  },
  {
    siteId: 3,
    speciesName: "Euconulus alderi",
    specification: "",
    live: 11,
    empty: 18,
    all: 29,
    lot: "",
    voucher: 10,
    note: "",
  },
  {
    siteId: 3,
    speciesName: "Nesovitrea hammonis",
    specification: "",
    live: 33,
    empty: 14,
    all: 47,
    lot: "",
    voucher: "",
    note: "",
  },
  {
    siteId: 3,
    speciesName: "Carychium minimum",
    specification: "juv.",
    live: 1,
    empty: 2,
    all: 3,
    lot: "",
    voucher: "",
    note: "",
  },
  {
    siteId: 3,
    speciesName: "Punctum pygmaeum",
    specification: "",
    live: 0,
    empty: 3,
    all: 3,
    lot: "",
    voucher: "",
    note: "",
  },
  {
    siteId: 3,
    speciesName: "Vertigo substriata",
    specification: "",
    live: 3,
    empty: 6,
    all: 9,
    lot: "",
    voucher: "",
    note: "",
  },
  {
    siteId: 3,
    speciesName: "Cochlicopa lubrica",
    specification: "",
    live: 31,
    empty: 14,
    all: 45,
    lot: "",
    voucher: "",
    note: "",
  },
  {
    siteId: 3,
    speciesName: "Trochulus hispidus",
    specification: "",
    live: 2,
    empty: 1,
    all: 3,
    lot: "",
    voucher: "",
    note: "",
  },
  {
    siteId: 3,
    speciesName: "Euconulus fulvus",
    specification: "",
    live: 4,
    empty: 3,
    all: 7,
    lot: "",
    voucher: "",
    note: "",
  },
  {
    siteId: 3,
    speciesName: "Oxyloma elegans",
    specification: "",
    live: 0,
    empty: 1,
    all: 1,
    lot: "",
    voucher: "",
    note: "pitva",
  },
];
