export const backup = [
  {
    speciesName: "Abida secale",
    abbreviation: "AbiSec",
    group: "Terrestrial",
    speciesAndAuthor: "Abida secale (Draparnaud, 1801)",
    note: "",
  },
  {
    speciesName: "Acanthinula aculeata",
    abbreviation: "AcaAcu",
    group: "Terrestrial",
    speciesAndAuthor: "Acanthinula aculeata (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Acicula parcelineata",
    abbreviation: "AciPar",
    group: "Aquatic",
    speciesAndAuthor: "Acicula parcelineata (Clessin, 1911)",
    note: "",
  },
  {
    speciesName: "Acroloxus lacustris",
    abbreviation: "AcrLac",
    group: "Aquatic",
    speciesAndAuthor: "Acroloxus lacustris (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Aegopinella epipedostoma",
    abbreviation: "AegEpi",
    group: "Terrestrial",
    speciesAndAuthor: "Aegopinella epipedostoma iuncta Hudec, 1964",
    note: "",
  },
  {
    speciesName: "Aegopinella minor",
    abbreviation: "AegMin",
    group: "Terrestrial",
    speciesAndAuthor: "Aegopinella minor (Stabile, 1864)",
    note: "",
  },
  {
    speciesName: "Aegopinella nitens",
    abbreviation: "AegNit",
    group: "Terrestrial",
    speciesAndAuthor: "Aegopinella nitens (Michaud, 1831)",
    note: "",
  },
  {
    speciesName: "Aegopinella nitidula",
    abbreviation: "AegNit",
    group: "Terrestrial",
    speciesAndAuthor: "Aegopinella nitidula (Draparnaud, 1805)",
    note: "",
  },
  {
    speciesName: "Aegopinella pura",
    abbreviation: "AegPur",
    group: "Terrestrial",
    speciesAndAuthor: "Aegopinella pura (Alder, 1830)",
    note: "",
  },
  {
    speciesName: "Aegopinella ressmanni",
    abbreviation: "AegRes",
    group: "Terrestrial",
    speciesAndAuthor: "Aegopinella ressmanni (Westerlund, 1883)",
    note: "",
  },
  {
    speciesName: "Aegopis verticillus",
    abbreviation: "AegVer",
    group: "Terrestrial",
    speciesAndAuthor: "Aegopis verticillus (Lamarck, 1822)",
    note: "",
  },
  {
    speciesName: "Alinda biplicata",
    abbreviation: "AliBip",
    group: "Terrestrial",
    speciesAndAuthor: "Alinda biplicata (Montagu, 1803)",
    note: "",
  },
  {
    speciesName: "Alopia bielzi",
    abbreviation: "AloBie",
    group: "Terrestrial",
    speciesAndAuthor: "Alopia bielzi clathrata (E. A. Bielz, 1856)",
    note: "",
  },
  {
    speciesName: "Alzoniella slovenica",
    abbreviation: "AlzSlo",
    group: "Aquatic",
    speciesAndAuthor: "Alzoniella slovenica (Ložek et Brtek, 1964)",
    note: "",
  },
  {
    speciesName: "Ancylus fluviatilis",
    abbreviation: "AncFlu",
    group: "Aquatic",
    speciesAndAuthor: "Ancylus fluviatilis O. F. Müller, 1774",
    note: "",
  },
  {
    speciesName: "Anisus leucostoma",
    abbreviation: "AniLeu",
    group: "Aquatic",
    speciesAndAuthor: "Anisus leucostoma (Millet, 1813)",
    note: "",
  },
  {
    speciesName: "Anisus septemgyratus",
    abbreviation: "AniSep",
    group: "Aquatic",
    speciesAndAuthor: "Anisus septemgyratus (Rossmässler, 1835)",
    note: "",
  },
  {
    speciesName: "Anisus spirorbis",
    abbreviation: "AniSpi",
    group: "Aquatic",
    speciesAndAuthor: "Anisus spirorbis (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Anisus vortex",
    abbreviation: "AniVor",
    group: "Aquatic",
    speciesAndAuthor: "Anisus vortex (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Anisus vorticulus",
    abbreviation: "AniVor",
    group: "Aquatic",
    speciesAndAuthor: "Anisus vorticulus (Troschel, 1834)",
    note: "",
  },
  {
    speciesName: "Anodonta anatina",
    abbreviation: "AnoAna",
    group: "Aquatic",
    speciesAndAuthor: "Anodonta anatina (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Anodonta cygnea",
    abbreviation: "AnoCyg",
    group: "Aquatic",
    speciesAndAuthor: "Anodonta cygnea (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Aplexa hypnorum",
    abbreviation: "AplHyp",
    group: "Aquatic",
    speciesAndAuthor: "Aplexa hypnorum (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Argna bielzi",
    abbreviation: "ArgBie",
    group: "Terrestrial",
    speciesAndAuthor: "Argna bielzi (Rossmässler, 1859)",
    note: "",
  },
  {
    speciesName: "Arianta arbustorum",
    abbreviation: "AriArb",
    group: "Terrestrial",
    speciesAndAuthor: "Arianta arbustorum (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Arion circumscriptus",
    abbreviation: "AriCir",
    group: "Terrestrial",
    speciesAndAuthor: "Arion circumscriptus Johnston, 1828",
    note: "",
  },
  {
    speciesName: "Arion distinctus",
    abbreviation: "AriDis",
    group: "Terrestrial",
    speciesAndAuthor: "Arion distinctus Mabille, 1868",
    note: "",
  },
  {
    speciesName: "Arion fasciatus",
    abbreviation: "AriFas",
    group: "Terrestrial",
    speciesAndAuthor: "Arion fasciatus (Nilsson, 1823)",
    note: "",
  },
  {
    speciesName: "Arion fuscus",
    abbreviation: "AriFus",
    group: "Terrestrial",
    speciesAndAuthor: "Arion fuscus (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Arion intermedius",
    abbreviation: "AriInt",
    group: "Terrestrial",
    speciesAndAuthor: "Arion intermedius Normand, 1852",
    note: "",
  },
  {
    speciesName: "Arion obesoductus",
    abbreviation: "AriObe",
    group: "Terrestrial",
    speciesAndAuthor: "Arion obesoductus Reischütz, 1973",
    note: "",
  },
  {
    speciesName: "Arion rufus",
    abbreviation: "AriRuf",
    group: "Terrestrial",
    speciesAndAuthor: "Arion rufus (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Arion silvaticus",
    abbreviation: "AriSil",
    group: "Terrestrial",
    speciesAndAuthor: "Arion silvaticus Lohmander, 1937",
    note: "",
  },
  {
    speciesName: "Arion vulgaris",
    abbreviation: "AriVul",
    group: "Terrestrial",
    speciesAndAuthor: "Arion vulgaris Moquin-Tandon, 1855",
    note: "",
  },
  {
    speciesName: "Azeca goodalli",
    abbreviation: "AzeGoo",
    group: "Terrestrial",
    speciesAndAuthor: "Azeca goodalli (A. Férussac, 1821)",
    note: "",
  },
  {
    speciesName: "Balea perversa",
    abbreviation: "BalPer",
    group: "Terrestrial",
    speciesAndAuthor: "Balea perversa (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Bathyomphalus contortus",
    abbreviation: "BatCon",
    group: "Aquatic",
    speciesAndAuthor: "Bathyomphalus contortus (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Bielzia coerulans",
    abbreviation: "BieCoe",
    group: "Terrestrial",
    speciesAndAuthor: "Bielzia coerulans (M. Bielz, 1851)",
    note: "",
  },
  {
    speciesName: "Bithynia leachii",
    abbreviation: "BitLea",
    group: "Aquatic",
    speciesAndAuthor: "Bithynia leachii (Sheppard, 1823)",
    note: "",
  },
  {
    speciesName: "Bithynia tentaculata",
    abbreviation: "BitTen",
    group: "Aquatic",
    speciesAndAuthor: "Bithynia tentaculata (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Bithynia transsilvanica",
    abbreviation: "BitTra",
    group: "Aquatic",
    speciesAndAuthor: "Bithynia transsilvanica (Bielz, 1853)",
    note: "",
  },
  {
    speciesName: "Boettgerilla pallens",
    abbreviation: "BoePal",
    group: "Terrestrial",
    speciesAndAuthor: "Boettgerilla pallens Simroth, 1912",
    note: "",
  },
  {
    speciesName: "Borysthenia naticina",
    abbreviation: "BorNat",
    group: "Aquatic",
    speciesAndAuthor: "Borysthenia naticina (Menke, 1845)",
    note: "",
  },
  {
    speciesName: "Bulgarica cana",
    abbreviation: "BulCan",
    group: "Terrestrial",
    speciesAndAuthor: "Bulgarica cana (Held, 1836)",
    note: "",
  },
  {
    speciesName: "Bulgarica fritillaria",
    abbreviation: "BulFri",
    group: "Terrestrial",
    speciesAndAuthor: "Bulgarica fritillaria (Frivaldszky, 1835)",
    note: "",
  },
  {
    speciesName: "Bulgarica nitidosa",
    abbreviation: "BulNit",
    group: "Terrestrial",
    speciesAndAuthor: "Bulgarica nitidosa (Uličný, 1893)",
    note: "",
  },
  {
    speciesName: "Bythinella austriaca",
    abbreviation: "BytAus",
    group: "Aquatic",
    speciesAndAuthor: "Bythinella austriaca (von Frauenfeld, 1857)",
    note: "",
  },
  {
    speciesName: "Bythinella hansboetersi",
    abbreviation: "BytHan",
    group: "Aquatic",
    speciesAndAuthor: "Bythinella hansboetersi Glöer et Pešić, 2006",
    note: "",
  },
  {
    speciesName: "Bythinella pannonica",
    abbreviation: "BytPan",
    group: "Aquatic",
    speciesAndAuthor: "Bythinella pannonica (von Frauenfeld, 1865)",
    note: "",
  },
  {
    speciesName: "Bythinella rufescens",
    abbreviation: "BytRuf",
    group: "Aquatic",
    speciesAndAuthor: "Bythinella rufescens (Küster, 1852)",
    note: "",
  },
  {
    speciesName: "Bythinella schmidti",
    abbreviation: "BytSch",
    group: "Aquatic",
    speciesAndAuthor: "Bythinella schmidti (Küster, 1852)",
    note: "",
  },
  {
    speciesName: "Candidula unifasciata",
    abbreviation: "CanUni",
    group: "Terrestrial",
    speciesAndAuthor: "Candidula unifasciata (Poiret, 1801)",
    note: "",
  },
  {
    speciesName: "Carpathica calophana",
    abbreviation: "CarCal",
    group: "Terrestrial",
    speciesAndAuthor: "Carpathica calophana (Westerlund, 1881)",
    note: "",
  },
  {
    speciesName: "Carychium minimum",
    abbreviation: "CarMin",
    group: "Terrestrial",
    speciesAndAuthor: "Carychium minimum O. F. Müller, 1774",
    note: "",
  },
  {
    speciesName: "Carychium tridentatum",
    abbreviation: "CarTri",
    group: "Terrestrial",
    speciesAndAuthor: "Carychium tridentatum (Risso, 1826)",
    note: "",
  },
  {
    speciesName: "Catascopia terebra",
    abbreviation: "CatTer",
    group: "Aquatic",
    speciesAndAuthor: "Catascopia terebra (Westerlund, 1885)",
    note: "",
  },
  {
    speciesName: "Caucasotachea vindobonensis",
    abbreviation: "CauVin",
    group: "Terrestrial",
    speciesAndAuthor: "Caucasotachea vindobonensis (C. Pfeiffer, 1828)",
    note: "",
  },
  {
    speciesName: "Causa holosericea",
    abbreviation: "CauHol",
    group: "Terrestrial",
    speciesAndAuthor: "Causa holosericea (Studer, 1820)",
    note: "",
  },
  {
    speciesName: "Cecilioides acicula",
    abbreviation: "CecAci",
    group: "Terrestrial",
    speciesAndAuthor: "Cecilioides acicula (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Cecilioides petitiana",
    abbreviation: "CecPet",
    group: "Terrestrial",
    speciesAndAuthor: "Cecilioides petitiana (Benoit, 1862)",
    note: "",
  },
  {
    speciesName: "Cepaea hortensis",
    abbreviation: "CepHor",
    group: "Terrestrial",
    speciesAndAuthor: "Cepaea hortensis (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Cepaea nemoralis",
    abbreviation: "CepNem",
    group: "Terrestrial",
    speciesAndAuthor: "Cepaea nemoralis (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Cernuella neglecta",
    abbreviation: "CerNeg",
    group: "Terrestrial",
    speciesAndAuthor: "Cernuella neglecta (Draparnaud, 1805)",
    note: "",
  },
  {
    speciesName: "Clausilia bidentata",
    abbreviation: "ClaBid",
    group: "Terrestrial",
    speciesAndAuthor: "Clausilia bidentata (Ström, 1765)",
    note: "",
  },
  {
    speciesName: "Clausilia cruciata",
    abbreviation: "ClaCru",
    group: "Terrestrial",
    speciesAndAuthor: "Clausilia cruciata (Studer, 1820)",
    note: "",
  },
  {
    speciesName: "Clausilia dubia",
    abbreviation: "ClaDub",
    group: "Terrestrial",
    speciesAndAuthor: "Clausilia dubia Draparnaud, 1805",
    note: "",
  },
  {
    speciesName: "Clausilia pumila",
    abbreviation: "ClaPum",
    group: "Terrestrial",
    speciesAndAuthor: "Clausilia pumila C. Pfeiffer, 1828",
    note: "",
  },
  {
    speciesName: "Clausilia rugosa",
    abbreviation: "ClaRug",
    group: "Terrestrial",
    speciesAndAuthor: "Clausilia rugosa (Draparnaud, 1801)",
    note: "",
  },
  {
    speciesName: "Cochlicopa lubrica",
    abbreviation: "CocLub",
    group: "Terrestrial",
    speciesAndAuthor: "Cochlicopa lubrica (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Cochlicopa lubricella",
    abbreviation: "CocLub",
    group: "Terrestrial",
    speciesAndAuthor: "Cochlicopa lubricella (Porro, 1838)",
    note: "",
  },
  {
    speciesName: "Cochlicopa nitens",
    abbreviation: "CocNit",
    group: "Terrestrial",
    speciesAndAuthor: "Cochlicopa nitens (M. von Gallenstein, 1848)",
    note: "Specialist",
  },
  {
    speciesName: "Cochlodina cerata",
    abbreviation: "CocCer",
    group: "Terrestrial",
    speciesAndAuthor: "Cochlodina cerata (Rossmässler, 1836)",
    note: "",
  },
  {
    speciesName: "Cochlodina costata",
    abbreviation: "CocCos",
    group: "Terrestrial",
    speciesAndAuthor: "Cochlodina costata (C. Pfeiffer, 1828)",
    note: "",
  },
  {
    speciesName: "Cochlodina dubiosa",
    abbreviation: "CocDub",
    group: "Terrestrial",
    speciesAndAuthor: "Cochlodina dubiosa corcontica Brabenec, 1967",
    note: "",
  },
  {
    speciesName: "Cochlodina fimbriata",
    abbreviation: "CocFim",
    group: "Terrestrial",
    speciesAndAuthor: "Cochlodina fimbriata (Rossmässler, 1835)",
    note: "",
  },
  {
    speciesName: "Cochlodina laminata",
    abbreviation: "CocLam",
    group: "Terrestrial",
    speciesAndAuthor: "Cochlodina laminata (Montagu, 1803)",
    note: "",
  },
  {
    speciesName: "Cochlodina orthostoma",
    abbreviation: "CocOrt",
    group: "Terrestrial",
    speciesAndAuthor: "Cochlodina orthostoma (Menke, 1828)",
    note: "",
  },
  {
    speciesName: "Cochlostoma septemspirale",
    abbreviation: "CocSep",
    group: "Terrestrial",
    speciesAndAuthor: "Cochlostoma septemspirale (Razoumowsky, 1789)",
    note: "",
  },
  {
    speciesName: "Columella aspera",
    abbreviation: "ColAsp",
    group: "Terrestrial",
    speciesAndAuthor: "Columella aspera Waldén, 1966",
    note: "",
  },
  {
    speciesName: "Columella columella",
    abbreviation: "ColCol",
    group: "Terrestrial",
    speciesAndAuthor: "Columella columella (G. von Martens, 1830)",
    note: "Relict",
  },
  {
    speciesName: "Columella edentula",
    abbreviation: "ColEde",
    group: "Terrestrial",
    speciesAndAuthor: "Columella edentula (Draparnaud, 1805)",
    note: "",
  },
  {
    speciesName: "Corbicula fluminea",
    abbreviation: "CorFlu",
    group: "Aquatic",
    speciesAndAuthor: "Corbicula fluminea (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Cornu aspersum",
    abbreviation: "CorAsp",
    group: "Terrestrial",
    speciesAndAuthor: "Cornu aspersum (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Daudebardia brevipes",
    abbreviation: "DauBre",
    group: "Terrestrial",
    speciesAndAuthor: "Daudebardia brevipes (Draparnaud, 1805)",
    note: "",
  },
  {
    speciesName: "Daudebardia rufa",
    abbreviation: "DauRuf",
    group: "Terrestrial",
    speciesAndAuthor: "Daudebardia rufa (Draparnaud, 1805)",
    note: "",
  },
  {
    speciesName: "Deroceras agreste",
    abbreviation: "DerAgr",
    group: "Terrestrial",
    speciesAndAuthor: "Deroceras agreste (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Deroceras invadens",
    abbreviation: "DerInv",
    group: "Terrestrial",
    speciesAndAuthor:
      "Deroceras invadens Reise, Hutchinson, Schunack et Schlitt, 2011",
    note: "",
  },
  {
    speciesName: "Deroceras juranum",
    abbreviation: "DerJur",
    group: "Terrestrial",
    speciesAndAuthor: "Deroceras juranum Wüthrich, 1993",
    note: "",
  },
  {
    speciesName: "Deroceras laeve",
    abbreviation: "DerLae",
    group: "Terrestrial",
    speciesAndAuthor: "Deroceras laeve (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Deroceras praecox",
    abbreviation: "DerPra",
    group: "Terrestrial",
    speciesAndAuthor: "Deroceras praecox Wiktor, 1966",
    note: "",
  },
  {
    speciesName: "Deroceras reticulatum",
    abbreviation: "DerRet",
    group: "Terrestrial",
    speciesAndAuthor: "Deroceras reticulatum (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Deroceras rodnae",
    abbreviation: "DerRod",
    group: "Terrestrial",
    speciesAndAuthor: "Deroceras rodnae Grossu et Lupu, 1965",
    note: "",
  },
  {
    speciesName: "Deroceras sturanyi",
    abbreviation: "DerStu",
    group: "Terrestrial",
    speciesAndAuthor: "Deroceras sturanyi (Simroth, 1894)",
    note: "",
  },
  {
    speciesName: "Deroceras turcicum",
    abbreviation: "DerTur",
    group: "Terrestrial",
    speciesAndAuthor: "Deroceras turcicum (Simroth, 1894)",
    note: "",
  },
  {
    speciesName: "Discus perspectivus",
    abbreviation: "DisPer",
    group: "Terrestrial",
    speciesAndAuthor: "Discus perspectivus (M. von Mühlfeld, 1816)",
    note: "",
  },
  {
    speciesName: "Discus rotundatus",
    abbreviation: "DisRot",
    group: "Terrestrial",
    speciesAndAuthor: "Discus rotundatus (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Discus ruderatus",
    abbreviation: "DisRud",
    group: "Terrestrial",
    speciesAndAuthor: "Discus ruderatus (Hartmann, 1821)",
    note: "",
  },
  {
    speciesName: "Dreissena polymorpha",
    abbreviation: "DrePol",
    group: "Aquatic",
    speciesAndAuthor: "Dreissena polymorpha (Pallas, 1771)",
    note: "",
  },
  {
    speciesName: "Dreissena rostriformis",
    abbreviation: "DreRos",
    group: "Aquatic",
    speciesAndAuthor: "Dreissena rostriformis (Deshayes, 1838)",
    note: "",
  },
  {
    speciesName: "Ena montana",
    abbreviation: "EnaMon",
    group: "Terrestrial",
    speciesAndAuthor: "Ena montana (Draparnaud, 1801)",
    note: "",
  },
  {
    speciesName: "Esperiana daudebartii",
    abbreviation: "EspDau",
    group: "Aquatic",
    speciesAndAuthor: "Esperiana daudebartii acicularis (A. Férussac, 1823)",
    note: "",
  },
  {
    speciesName: "Esperiana esperi",
    abbreviation: "EspEsp",
    group: "Aquatic",
    speciesAndAuthor: "Esperiana esperi (A. Férussac, 1823)",
    note: "",
  },
  {
    speciesName: "Eucobresia diaphana",
    abbreviation: "EucDia",
    group: "Terrestrial",
    speciesAndAuthor: "Eucobresia diaphana (Draparnaud, 1805)",
    note: "",
  },
  {
    speciesName: "Eucobresia nivalis",
    abbreviation: "EucNiv",
    group: "Terrestrial",
    speciesAndAuthor: "Eucobresia nivalis (Dumont et Mortillet, 1854)",
    note: "",
  },
  {
    speciesName: "Euconulus alderi",
    abbreviation: "EucAld",
    group: "Terrestrial",
    speciesAndAuthor: "Euconulus alderi (Reinhardt, 1883)",
    note: "Specialist",
  },
  {
    speciesName: "Euconulus fulvus",
    abbreviation: "EucFul",
    group: "Terrestrial",
    speciesAndAuthor: "Euconulus fulvus (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Euomphalia strigella",
    abbreviation: "EuoStr",
    group: "Terrestrial",
    speciesAndAuthor: "Euomphalia strigella (Draparnaud, 1801)",
    note: "",
  },
  {
    speciesName: "Faustina cingulella",
    abbreviation: "FauCin",
    group: "Terrestrial",
    speciesAndAuthor: "Faustina cingulella (Rossmässler, 1837)",
    note: "",
  },
  {
    speciesName: "Faustina faustina",
    abbreviation: "FauFau",
    group: "Terrestrial",
    speciesAndAuthor: "Faustina faustina (Rossmässler, 1835)",
    note: "",
  },
  {
    speciesName: "Faustina rossmaessleri",
    abbreviation: "FauRos",
    group: "Terrestrial",
    speciesAndAuthor: "Faustina rossmaessleri (L. Pfeiffer, 1848)",
    note: "",
  },
  {
    speciesName: "Ferrissia californica",
    abbreviation: "FerCal",
    group: "Aquatic",
    speciesAndAuthor: "Ferrissia californica (Rowell, 1863)",
    note: "",
  },
  {
    speciesName: "Fruticicola fruticum",
    abbreviation: "FruFru",
    group: "Terrestrial",
    speciesAndAuthor: "Fruticicola fruticum (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Galba truncatula",
    abbreviation: "GalTru",
    group: "Aquatic",
    speciesAndAuthor: "Galba truncatula (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Granaria frumentum",
    abbreviation: "GraFru",
    group: "Terrestrial",
    speciesAndAuthor: "Granaria frumentum (Draparnaud, 1801)",
    note: "",
  },
  {
    speciesName: "Gyraulus acronicus",
    abbreviation: "GyrAcr",
    group: "Aquatic",
    speciesAndAuthor: "Gyraulus acronicus (A. Férussac, 1807)",
    note: "",
  },
  {
    speciesName: "Gyraulus albus",
    abbreviation: "GyrAlb",
    group: "Aquatic",
    speciesAndAuthor: "Gyraulus albus (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Gyraulus crista",
    abbreviation: "GyrCri",
    group: "Aquatic",
    speciesAndAuthor: "Gyraulus crista (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Gyraulus laevis",
    abbreviation: "GyrLae",
    group: "Aquatic",
    speciesAndAuthor: "Gyraulus laevis (Alder, 1838)",
    note: "",
  },
  {
    speciesName: "Gyraulus parvus",
    abbreviation: "GyrPar",
    group: "Aquatic",
    speciesAndAuthor: "Gyraulus parvus (Say, 1817)",
    note: "",
  },
  {
    speciesName: "Gyraulus riparius",
    abbreviation: "GyrRip",
    group: "Aquatic",
    speciesAndAuthor: "Gyraulus riparius (Westerlund, 1865)",
    note: "",
  },
  {
    speciesName: "Gyraulus rossmaessleri",
    abbreviation: "GyrRos",
    group: "Aquatic",
    speciesAndAuthor: "Gyraulus rossmaessleri (Schmidt, 1852)",
    note: "",
  },
  {
    speciesName: "Hauffenia sp.",
    abbreviation: "HauSp.",
    group: "Aquatic",
    speciesAndAuthor: "Hauffenia sp. (undescribed sp.)",
    note: "",
  },
  {
    speciesName: "Helicella itala",
    abbreviation: "HelIta",
    group: "Terrestrial",
    speciesAndAuthor: "Helicella itala (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Helicigona lapicida",
    abbreviation: "HelLap",
    group: "Terrestrial",
    speciesAndAuthor: "Helicigona lapicida (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Helicodonta obvoluta",
    abbreviation: "HelObv",
    group: "Terrestrial",
    speciesAndAuthor: "Helicodonta obvoluta (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Helicopsis striata",
    abbreviation: "HelStr",
    group: "Terrestrial",
    speciesAndAuthor: "Helicopsis striata (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Helix lucorum",
    abbreviation: "HelLuc",
    group: "Terrestrial",
    speciesAndAuthor: "Helix lucorum Linné, 1758",
    note: "",
  },
  {
    speciesName: "Helix lutescens",
    abbreviation: "HelLut",
    group: "Terrestrial",
    speciesAndAuthor: "Helix lutescens Rossmässler, 1837",
    note: "",
  },
  {
    speciesName: "Helix pomatia",
    abbreviation: "HelPom",
    group: "Terrestrial",
    speciesAndAuthor: "Helix pomatia Linné, 1758",
    note: "",
  },
  {
    speciesName: "Helix thessalica",
    abbreviation: "HelThe",
    group: "Terrestrial",
    speciesAndAuthor: "Helix thessalica Boettger, 1886",
    note: "",
  },
  {
    speciesName: "Hippeutis complanatus",
    abbreviation: "HipCom",
    group: "Aquatic",
    speciesAndAuthor: "Hippeutis complanatus (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Hygromia cinctella",
    abbreviation: "HygCin",
    group: "Terrestrial",
    speciesAndAuthor: "Hygromia cinctella (Draparnaud, 1801)",
    note: "",
  },
  {
    speciesName: "Charpentieria ornata",
    abbreviation: "ChaOrn",
    group: "Terrestrial",
    speciesAndAuthor: "Charpentieria ornata (Rossmässler, 1836)",
    note: "",
  },
  {
    speciesName: "Chondrina arcadica",
    abbreviation: "ChoArc",
    group: "Terrestrial",
    speciesAndAuthor: "Chondrina arcadica clienta (Westerlund, 1883)",
    note: "",
  },
  {
    speciesName: "Chondrina avenacea",
    abbreviation: "ChoAve",
    group: "Terrestrial",
    speciesAndAuthor: "Chondrina avenacea (Bruguière, 1792)",
    note: "",
  },
  {
    speciesName: "Chondrina tatrica",
    abbreviation: "ChoTat",
    group: "Terrestrial",
    speciesAndAuthor: "Chondrina tatrica Ložek, 1948",
    note: "",
  },
  {
    speciesName: "Chondrula tridens",
    abbreviation: "ChoTri",
    group: "Terrestrial",
    speciesAndAuthor: "Chondrula tridens (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Isognomostoma isognomostomos",
    abbreviation: "IsoIso",
    group: "Terrestrial",
    speciesAndAuthor: "Isognomostoma isognomostomos (Schröter, 1784)",
    note: "",
  },
  {
    speciesName: "Laciniaria plicata",
    abbreviation: "LacPli",
    group: "Terrestrial",
    speciesAndAuthor: "Laciniaria plicata (Draparnaud, 1801)",
    note: "",
  },
  {
    speciesName: "Ladislavella occulta",
    abbreviation: "LadOcc",
    group: "Aquatic",
    speciesAndAuthor: "Ladislavella occulta (Jackiewicz, 1959)",
    note: "",
  },
  {
    speciesName: "Lehmannia macroflagellata",
    abbreviation: "LehMac",
    group: "Terrestrial",
    speciesAndAuthor: "Lehmannia macroflagellata Grossu et Lupu, 1962",
    note: "",
  },
  {
    speciesName: "Lehmannia marginata",
    abbreviation: "LehMar",
    group: "Terrestrial",
    speciesAndAuthor: "Lehmannia marginata (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Lehmannia nyctelia",
    abbreviation: "LehNyc",
    group: "Terrestrial",
    speciesAndAuthor: "Lehmannia nyctelia (Bourguignat, 1861)",
    note: "",
  },
  {
    speciesName: "Limacus flavus",
    abbreviation: "LimFla",
    group: "Terrestrial",
    speciesAndAuthor: "Limacus flavus (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Limax cinereoniger",
    abbreviation: "LimCin",
    group: "Terrestrial",
    speciesAndAuthor: "Limax cinereoniger Wolf, 1803",
    note: "",
  },
  {
    speciesName: "Limax maximus",
    abbreviation: "LimMax",
    group: "Terrestrial",
    speciesAndAuthor: "Limax maximus Linné, 1758",
    note: "",
  },
  {
    speciesName: "Lithoglyphus naticoides",
    abbreviation: "LitNat",
    group: "Aquatic",
    speciesAndAuthor: "Lithoglyphus naticoides (C. Pfeiffer, 1828)",
    note: "",
  },
  {
    speciesName: "Lozekia transsilvanica",
    abbreviation: "LozTra",
    group: "Terrestrial",
    speciesAndAuthor: "Lozekia transsilvanica (Westerlund, 1876)",
    note: "",
  },
  {
    speciesName: "Lucilla scintilla",
    abbreviation: "LucSci",
    group: "Terrestrial",
    speciesAndAuthor: "Lucilla scintilla (R. T. Lowe, 1852)",
    note: "",
  },
  {
    speciesName: "Lucilla singleyana",
    abbreviation: "LucSin",
    group: "Terrestrial",
    speciesAndAuthor: "Lucilla singleyana (Pilsbry, 1889)",
    note: "",
  },
  {
    speciesName: "Lymnaea stagnalis",
    abbreviation: "LymSta",
    group: "Aquatic",
    speciesAndAuthor: "Lymnaea stagnalis (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Macrogastra badia",
    abbreviation: "MacBad",
    group: "Terrestrial",
    speciesAndAuthor: "Macrogastra badia (C. Pfeiffer, 1828)",
    note: "",
  },
  {
    speciesName: "Macrogastra latestriata",
    abbreviation: "MacLat",
    group: "Terrestrial",
    speciesAndAuthor: "Macrogastra latestriata (A. Schmidt, 1856)",
    note: "",
  },
  {
    speciesName: "Macrogastra plicatula",
    abbreviation: "MacPli",
    group: "Terrestrial",
    speciesAndAuthor: "Macrogastra plicatula (Draparnaud, 1801)",
    note: "",
  },
  {
    speciesName: "Macrogastra tumida",
    abbreviation: "MacTum",
    group: "Terrestrial",
    speciesAndAuthor: "Macrogastra tumida (Rossmässler, 1835)",
    note: "",
  },
  {
    speciesName: "Macrogastra ventricosa",
    abbreviation: "MacVen",
    group: "Terrestrial",
    speciesAndAuthor: "Macrogastra ventricosa (Draparnaud, 1801)",
    note: "",
  },
  {
    speciesName: "Malacolimax tenellus",
    abbreviation: "MalTen",
    group: "Terrestrial",
    speciesAndAuthor: "Malacolimax tenellus (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Margaritifera margaritifera",
    abbreviation: "MarMar",
    group: "Aquatic",
    speciesAndAuthor: "Margaritifera margaritifera (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Marstoniopsis insubrica",
    abbreviation: "MarIns",
    group: "Aquatic",
    speciesAndAuthor: "Marstoniopsis insubrica (Küster, 1853)",
    note: "",
  },
  {
    speciesName: "Menetus dilatatus",
    abbreviation: "MenDil",
    group: "Aquatic",
    speciesAndAuthor: "Menetus dilatatus (Gould, 1841)",
    note: "",
  },
  {
    speciesName: "Merdigera obscura",
    abbreviation: "MerObs",
    group: "Terrestrial",
    speciesAndAuthor: "Merdigera obscura (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Monacha cartusiana",
    abbreviation: "MonCar",
    group: "Terrestrial",
    speciesAndAuthor: "Monacha cartusiana (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Monacha claustralis",
    abbreviation: "MonCla",
    group: "Terrestrial",
    speciesAndAuthor: "Monacha claustralis (Rossmässler, 1834)",
    note: "",
  },
  {
    speciesName: "Monachoides incarnatus",
    abbreviation: "MonInc",
    group: "Terrestrial",
    speciesAndAuthor: "Monachoides incarnatus (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Monachoides vicinus",
    abbreviation: "MonVic",
    group: "Terrestrial",
    speciesAndAuthor: "Monachoides vicinus (Rossmässler, 1842)",
    note: "",
  },
  {
    speciesName: "Musculium lacustre",
    abbreviation: "MusLac",
    group: "Aquatic",
    speciesAndAuthor: "Musculium lacustre (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Myxas glutinosa",
    abbreviation: "MyxGlu",
    group: "Aquatic",
    speciesAndAuthor: "Myxas glutinosa (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Nesovitrea hammonis",
    abbreviation: "NesHam",
    group: "Terrestrial",
    speciesAndAuthor: "Nesovitrea hammonis (Ström, 1765)",
    note: "",
  },
  {
    speciesName: "Nesovitrea petronella",
    abbreviation: "NesPet",
    group: "Terrestrial",
    speciesAndAuthor: "Nesovitrea petronella (L. Pfeiffer, 1853)",
    note: "Relict",
  },
  {
    speciesName: "Orcula dolium",
    abbreviation: "OrcDol",
    group: "Terrestrial",
    speciesAndAuthor: "Orcula dolium (Draparnaud, 1801)",
    note: "",
  },
  {
    speciesName: "Orculella bulgarica",
    abbreviation: "OrcBul",
    group: "Terrestrial",
    speciesAndAuthor: "Orculella bulgarica (Hesse, 1915)",
    note: "",
  },
  {
    speciesName: "Oxychilus alliarius",
    abbreviation: "OxyAll",
    group: "Terrestrial",
    speciesAndAuthor: "Oxychilus alliarius (Miller, 1822)",
    note: "",
  },
  {
    speciesName: "Oxychilus cellarius",
    abbreviation: "OxyCel",
    group: "Terrestrial",
    speciesAndAuthor: "Oxychilus cellarius (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Oxychilus depressus",
    abbreviation: "OxyDep",
    group: "Terrestrial",
    speciesAndAuthor: "Oxychilus depressus (Sterki, 1880)",
    note: "",
  },
  {
    speciesName: "Oxychilus deubeli",
    abbreviation: "OxyDeu",
    group: "Terrestrial",
    speciesAndAuthor: "Oxychilus deubeli (A. J. Wagner, 1914)",
    note: "",
  },
  {
    speciesName: "Oxychilus draparnaudi",
    abbreviation: "OxyDra",
    group: "Terrestrial",
    speciesAndAuthor: "Oxychilus draparnaudi (Beck, 1837)",
    note: "",
  },
  {
    speciesName: "Oxychilus glaber",
    abbreviation: "OxyGla",
    group: "Terrestrial",
    speciesAndAuthor: "Oxychilus glaber (Rossmässler, 1835)",
    note: "",
  },
  {
    speciesName: "Oxychilus hydatinus",
    abbreviation: "OxyHyd",
    group: "Terrestrial",
    speciesAndAuthor: "Oxychilus hydatinus (Rossmässler, 1838)",
    note: "",
  },
  {
    speciesName: "Oxychilus inopinatus",
    abbreviation: "OxyIno",
    group: "Terrestrial",
    speciesAndAuthor: "Oxychilus inopinatus (Uličný, 1887)",
    note: "",
  },
  {
    speciesName: "Oxychilus mortilleti",
    abbreviation: "OxyMor",
    group: "Terrestrial",
    speciesAndAuthor: "Oxychilus mortilleti (L. Pfeiffer, 1859)",
    note: "",
  },
  {
    speciesName: "Oxyloma elegans",
    abbreviation: "OxyEle",
    group: "Terrestrial",
    speciesAndAuthor: "Oxyloma elegans (Risso, 1826)",
    note: "",
  },
  {
    speciesName: "Pagodulina pagodula",
    abbreviation: "PagPag",
    group: "Terrestrial",
    speciesAndAuthor: "Pagodulina pagodula (Des Moulins, 1830)",
    note: "",
  },
  {
    speciesName: "Perforatella bidentata",
    abbreviation: "PerBid",
    group: "Terrestrial",
    speciesAndAuthor: "Perforatella bidentata (Gmelin, 1791)",
    note: "",
  },
  {
    speciesName: "Perforatella dibotrion",
    abbreviation: "PerDib",
    group: "Terrestrial",
    speciesAndAuthor: "Perforatella dibotrion (E. A. Bielz, 1860)",
    note: "",
  },
  {
    speciesName: "Petasina bakowskii",
    abbreviation: "PetBak",
    group: "Terrestrial",
    speciesAndAuthor: "Petasina bakowskii (Poliński, 1924)",
    note: "",
  },
  {
    speciesName: "Petasina bielzi",
    abbreviation: "PetBie",
    group: "Terrestrial",
    speciesAndAuthor: "Petasina bielzi (E. A. Bielz, 1860)",
    note: "",
  },
  {
    speciesName: "Petasina edentula",
    abbreviation: "PetEde",
    group: "Terrestrial",
    speciesAndAuthor: "Petasina edentula (Draparnaud, 1805)",
    note: "",
  },
  {
    speciesName: "Petasina filicina",
    abbreviation: "PetFil",
    group: "Terrestrial",
    speciesAndAuthor: "Petasina filicina (L. Pfeiffer, 1841)",
    note: "",
  },
  {
    speciesName: "Petasina unidentata",
    abbreviation: "PetUni",
    group: "Terrestrial",
    speciesAndAuthor: "Petasina unidentata (Draparnaud, 1805)",
    note: "",
  },
  {
    speciesName: "Physa acuta",
    abbreviation: "PhyAcu",
    group: "Aquatic",
    speciesAndAuthor: "Physa acuta Draparnaud, 1805",
    note: "",
  },
  {
    speciesName: "Physa fontinalis",
    abbreviation: "PhyFon",
    group: "Aquatic",
    speciesAndAuthor: "Physa fontinalis (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Pisidium amnicum",
    abbreviation: "PisAmn",
    group: "Aquatic",
    speciesAndAuthor: "Pisidium amnicum (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Pisidium casertanum",
    abbreviation: "PisCas",
    group: "Aquatic",
    speciesAndAuthor: "Pisidium casertanum (Poli, 1791)",
    note: "",
  },
  {
    speciesName: "Pisidium globulare",
    abbreviation: "PisGlo",
    group: "Aquatic",
    speciesAndAuthor: "Pisidium globulare Westerlund, 1873",
    note: "",
  },
  {
    speciesName: "Pisidium henslowanum",
    abbreviation: "PisHen",
    group: "Aquatic",
    speciesAndAuthor: "Pisidium henslowanum (Sheppard, 1823)",
    note: "",
  },
  {
    speciesName: "Pisidium hibernicum",
    abbreviation: "PisHib",
    group: "Aquatic",
    speciesAndAuthor: "Pisidium hibernicum Westerlund, 1894",
    note: "",
  },
  {
    speciesName: "Pisidium milium",
    abbreviation: "PisMil",
    group: "Aquatic",
    speciesAndAuthor: "Pisidium milium Held, 1836",
    note: "",
  },
  {
    speciesName: "Pisidium moitessierianum",
    abbreviation: "PisMoi",
    group: "Aquatic",
    speciesAndAuthor: "Pisidium moitessierianum Paladilhe, 1866",
    note: "",
  },
  {
    speciesName: "Pisidium nitidum",
    abbreviation: "PisNit",
    group: "Aquatic",
    speciesAndAuthor: "Pisidium nitidum Jenyns, 1832",
    note: "",
  },
  {
    speciesName: "Pisidium obtusale",
    abbreviation: "PisObt",
    group: "Aquatic",
    speciesAndAuthor: "Pisidium obtusale (Lamarck, 1818)",
    note: "",
  },
  {
    speciesName: "Pisidium personatum",
    abbreviation: "PisPer",
    group: "Aquatic",
    speciesAndAuthor: "Pisidium personatum Malm, 1855",
    note: "",
  },
  {
    speciesName: "Pisidium pseudosphaerium",
    abbreviation: "PisPse",
    group: "Aquatic",
    speciesAndAuthor: "Pisidium pseudosphaerium J. Favre, 1927",
    note: "",
  },
  {
    speciesName: "Pisidium subtruncatum",
    abbreviation: "PisSub",
    group: "Aquatic",
    speciesAndAuthor: "Pisidium subtruncatum Malm, 1855",
    note: "",
  },
  {
    speciesName: "Pisidium supinum",
    abbreviation: "PisSup",
    group: "Aquatic",
    speciesAndAuthor: "Pisidium supinum A. Schmidt, 1851",
    note: "",
  },
  {
    speciesName: "Pisidium tenuilineatum",
    abbreviation: "PisTen",
    group: "Aquatic",
    speciesAndAuthor: "Pisidium tenuilineatum Stelfox, 1918",
    note: "",
  },
  {
    speciesName: "Planorbarius corneus",
    abbreviation: "PlaCor",
    group: "Aquatic",
    speciesAndAuthor: "Planorbarius corneus (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Planorbis carinatus",
    abbreviation: "PlaCar",
    group: "Aquatic",
    speciesAndAuthor: "Planorbis carinatus O. F. Müller, 1774",
    note: "",
  },
  {
    speciesName: "Planorbis planorbis",
    abbreviation: "PlaPla",
    group: "Aquatic",
    speciesAndAuthor: "Planorbis planorbis (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Platyla lineata",
    abbreviation: "PlaLin",
    group: "Terrestrial",
    speciesAndAuthor: "Platyla lineata (Draparnaud, 1801)",
    note: "",
  },
  {
    speciesName: "Platyla polita",
    abbreviation: "PlaPol",
    group: "Aquatic",
    speciesAndAuthor: "Platyla polita (Hartmann, 1840)",
    note: "",
  },
  {
    speciesName: "Plicuteria lubomirski",
    abbreviation: "PliLub",
    group: "Terrestrial",
    speciesAndAuthor: "Plicuteria lubomirski (Ślósarski, 1881)",
    note: "",
  },
  {
    speciesName: "Potamopyrgus antipodarum",
    abbreviation: "PotAnt",
    group: "Aquatic",
    speciesAndAuthor: "Potamopyrgus antipodarum (Gray, 1843)",
    note: "",
  },
  {
    speciesName: "Pseudalinda stabilis",
    abbreviation: "PseSta",
    group: "Terrestrial",
    speciesAndAuthor: "Pseudalinda stabilis (L. Pfeiffer, 1847)",
    note: "",
  },
  {
    speciesName: "Pseudanodonta complanata",
    abbreviation: "PseCom",
    group: "Aquatic",
    speciesAndAuthor: "Pseudanodonta complanata (Rossmässler, 1835)",
    note: "",
  },
  {
    speciesName: "Pseudofusulus varians",
    abbreviation: "PseVar",
    group: "Terrestrial",
    speciesAndAuthor: "Pseudofusulus varians (C. Pfeiffer, 1828)",
    note: "",
  },
  {
    speciesName: "Pseudotrichia rubiginosa",
    abbreviation: "PseRub",
    group: "Terrestrial",
    speciesAndAuthor: "Pseudotrichia rubiginosa (Rossmässler, 1838)",
    note: "",
  },
  {
    speciesName: "Punctum pygmaeum",
    abbreviation: "PunPyg",
    group: "Terrestrial",
    speciesAndAuthor: "Punctum pygmaeum (Draparnaud, 1801)",
    note: "",
  },
  {
    speciesName: "Pupilla alpicola",
    abbreviation: "PupAlp",
    group: "Terrestrial",
    speciesAndAuthor: "Pupilla alpicola (Charpentier, 1837)",
    note: "Relict",
  },
  {
    speciesName: "Pupilla muscorum",
    abbreviation: "PupMus",
    group: "Terrestrial",
    speciesAndAuthor: "Pupilla muscorum (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Pupilla sterrii",
    abbreviation: "PupSte",
    group: "Terrestrial",
    speciesAndAuthor: "Pupilla sterrii (Forster, 1840)",
    note: "",
  },
  {
    speciesName: "Pupilla triplicata",
    abbreviation: "PupTri",
    group: "Terrestrial",
    speciesAndAuthor: "Pupilla triplicata (Studer, 1820)",
    note: "",
  },
  {
    speciesName: "Pyramidula pusilla",
    abbreviation: "PyrPus",
    group: "Terrestrial",
    speciesAndAuthor: "Pyramidula pusilla Gittenberger et Bank, 1996",
    note: "",
  },
  {
    speciesName: "Quickella arenaria",
    abbreviation: "QuiAre",
    group: "Terrestrial",
    speciesAndAuthor: "Quickella arenaria (Potiez et Michaud, 1838)",
    note: "Relict",
  },
  {
    speciesName: "Radix ampla",
    abbreviation: "RadAmp",
    group: "Aquatic",
    speciesAndAuthor: "Radix ampla (Hartmann, 1821)",
    note: "",
  },
  {
    speciesName: "Radix auricularia",
    abbreviation: "RadAur",
    group: "Aquatic",
    speciesAndAuthor: "Radix auricularia (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Radix balthica",
    abbreviation: "RadBal",
    group: "Aquatic",
    speciesAndAuthor: "Radix balthica (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Radix labiata",
    abbreviation: "RadLab",
    group: "Aquatic",
    speciesAndAuthor: "Radix labiata (Rossmässler, 1835)",
    note: "",
  },
  {
    speciesName: "Ruthenica filograna",
    abbreviation: "RutFil",
    group: "Terrestrial",
    speciesAndAuthor: "Ruthenica filograna (Rossmässler, 1836)",
    note: "",
  },
  {
    speciesName: "Segmentina nitida",
    abbreviation: "SegNit",
    group: "Aquatic",
    speciesAndAuthor: "Segmentina nitida (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Semilimax kotulae",
    abbreviation: "SemKot",
    group: "Terrestrial",
    speciesAndAuthor: "Semilimax kotulae (Westerlund, 1883)",
    note: "",
  },
  {
    speciesName: "Semilimax semilimax",
    abbreviation: "SemSem",
    group: "Terrestrial",
    speciesAndAuthor: "Semilimax semilimax (J. Férussac, 1802)",
    note: "",
  },
  {
    speciesName: "Sinanodonta woodiana",
    abbreviation: "SinWoo",
    group: "Aquatic",
    speciesAndAuthor: "Sinanodonta woodiana (Lea, 1834)",
    note: "",
  },
  {
    speciesName: "Spelaeodiscus triarius",
    abbreviation: "SpeTri",
    group: "Terrestrial",
    speciesAndAuthor: "Spelaeodiscus triarius tatricus (Hazay, 1883)",
    note: "",
  },
  {
    speciesName: "Sphaerium corneum",
    abbreviation: "SphCor",
    group: "Aquatic",
    speciesAndAuthor: "Sphaerium corneum (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Sphaerium nucleus",
    abbreviation: "SphNuc",
    group: "Aquatic",
    speciesAndAuthor: "Sphaerium nucleus (Studer, 1820)",
    note: "",
  },
  {
    speciesName: "Sphaerium rivicola",
    abbreviation: "SphRiv",
    group: "Aquatic",
    speciesAndAuthor: "Sphaerium rivicola (Lamarck, 1818)",
    note: "",
  },
  {
    speciesName: "Sphaerium solidum",
    abbreviation: "SphSol",
    group: "Aquatic",
    speciesAndAuthor: "Sphaerium solidum (Normand, 1844)",
    note: "",
  },
  {
    speciesName: "Sphyradium doliolum",
    abbreviation: "SphDol",
    group: "Terrestrial",
    speciesAndAuthor: "Sphyradium doliolum (Bruguière, 1792)",
    note: "",
  },
  {
    speciesName: "Stagnicola corvus",
    abbreviation: "StaCor",
    group: "Aquatic",
    speciesAndAuthor: "Stagnicola corvus (Gmelin, 1791)",
    note: "",
  },
  {
    speciesName: "Stagnicola fuscus",
    abbreviation: "StaFus",
    group: "Aquatic",
    speciesAndAuthor: "Stagnicola fuscus (C. Pfeiffer, 1821)",
    note: "",
  },
  {
    speciesName: "Stagnicola palustris",
    abbreviation: "StaPal",
    group: "Aquatic",
    speciesAndAuthor: "Stagnicola palustris (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Stagnicola turricula",
    abbreviation: "StaTur",
    group: "Aquatic",
    speciesAndAuthor: "Stagnicola turricula (Held, 1836)",
    note: "",
  },
  {
    speciesName: "Succinea putris",
    abbreviation: "SucPut",
    group: "Terrestrial",
    speciesAndAuthor: "Succinea putris (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Succinella oblonga",
    abbreviation: "SucObl",
    group: "Terrestrial",
    speciesAndAuthor: "Succinella oblonga (Draparnaud, 1801)",
    note: "",
  },
  {
    speciesName: "Tandonia budapestensis",
    abbreviation: "TanBud",
    group: "Terrestrial",
    speciesAndAuthor: "Tandonia budapestensis (Hazay, 1880)",
    note: "",
  },
  {
    speciesName: "Tandonia kusceri",
    abbreviation: "TanKus",
    group: "Terrestrial",
    speciesAndAuthor: "Tandonia kusceri (Wagner, 1931)",
    note: "",
  },
  {
    speciesName: "Tandonia rustica",
    abbreviation: "TanRus",
    group: "Terrestrial",
    speciesAndAuthor: "Tandonia rustica (Millet, 1843)",
    note: "",
  },
  {
    speciesName: "Theodoxus danubialis",
    abbreviation: "TheDan",
    group: "Aquatic",
    speciesAndAuthor: "Theodoxus danubialis (C. Pfeiffer, 1828)",
    note: "",
  },
  {
    speciesName: "Theodoxus fluviatilis",
    abbreviation: "TheFlu",
    group: "Aquatic",
    speciesAndAuthor: "Theodoxus fluviatilis (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Theodoxus transversalis",
    abbreviation: "TheTra",
    group: "Aquatic",
    speciesAndAuthor: "Theodoxus transversalis (C. Pfeiffer, 1828)",
    note: "",
  },
  {
    speciesName: "Trichia leucozona",
    abbreviation: "TriLeu",
    group: "Terrestrial",
    speciesAndAuthor: "Trichia leucozona (Ziegler In C. Pfeffer, 1828)",
    note: "",
  },
  {
    speciesName: "Trochulus hispidus",
    abbreviation: "TroHis",
    group: "Terrestrial",
    speciesAndAuthor: "Trochulus hispidus (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Trochulus striolatus",
    abbreviation: "TroStr",
    group: "Terrestrial",
    speciesAndAuthor: "Trochulus striolatus danubialis (Clessin, 1874)",
    note: "",
  },
  {
    speciesName: "Trochulus villosulus",
    abbreviation: "TroVil",
    group: "Terrestrial",
    speciesAndAuthor: "Trochulus villosulus (Rossmässler, 1838)",
    note: "",
  },
  {
    speciesName: "Truncatellina claustralis",
    abbreviation: "TruCla",
    group: "Terrestrial",
    speciesAndAuthor: "Truncatellina claustralis (Gredler, 1856)",
    note: "",
  },
  {
    speciesName: "Truncatellina costulata",
    abbreviation: "TruCos",
    group: "Terrestrial",
    speciesAndAuthor: "Truncatellina costulata (Nilsson, 1823)",
    note: "",
  },
  {
    speciesName: "Truncatellina cylindrica",
    abbreviation: "TruCyl",
    group: "Terrestrial",
    speciesAndAuthor: "Truncatellina cylindrica (A. Férussac, 1807)",
    note: "",
  },
  {
    speciesName: "Unio crassus",
    abbreviation: "UniCra",
    group: "Aquatic",
    speciesAndAuthor: "Unio crassus Philipsson, 1788",
    note: "",
  },
  {
    speciesName: "Unio pictorum",
    abbreviation: "UniPic",
    group: "Aquatic",
    speciesAndAuthor: "Unio pictorum (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Unio tumidus",
    abbreviation: "UniTum",
    group: "Aquatic",
    speciesAndAuthor: "Unio tumidus Philipsson, 1788",
    note: "",
  },
  {
    speciesName: "Urticicola umbrosus",
    abbreviation: "UrtUmb",
    group: "Terrestrial",
    speciesAndAuthor: "Urticicola umbrosus (C. Pfeiffer, 1828)",
    note: "",
  },
  {
    speciesName: "Vallonia costata",
    abbreviation: "ValCos",
    group: "Terrestrial",
    speciesAndAuthor: "Vallonia costata (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Vallonia declivis",
    abbreviation: "ValDec",
    group: "Terrestrial",
    speciesAndAuthor: "Vallonia declivis Sterki, 1893",
    note: "",
  },
  {
    speciesName: "Vallonia enniensis",
    abbreviation: "ValEnn",
    group: "Terrestrial",
    speciesAndAuthor: "Vallonia enniensis (Gredler, 1856)",
    note: "Specialist",
  },
  {
    speciesName: "Vallonia excentrica",
    abbreviation: "ValExc",
    group: "Terrestrial",
    speciesAndAuthor: "Vallonia excentrica Sterki, 1893",
    note: "",
  },
  {
    speciesName: "Vallonia pulchella",
    abbreviation: "ValPul",
    group: "Terrestrial",
    speciesAndAuthor: "Vallonia pulchella (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Valvata cristata",
    abbreviation: "ValCri",
    group: "Aquatic",
    speciesAndAuthor: "Valvata cristata O. F. Müller, 1774",
    note: "",
  },
  {
    speciesName: "Valvata macrostoma",
    abbreviation: "ValMac",
    group: "Aquatic",
    speciesAndAuthor: "Valvata macrostoma Mörch, 1864",
    note: "",
  },
  {
    speciesName: "Valvata piscinalis",
    abbreviation: "ValPis",
    group: "Aquatic",
    speciesAndAuthor: "Valvata piscinalis (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Vertigo alpestris",
    abbreviation: "VerAlp",
    group: "Terrestrial",
    speciesAndAuthor: "Vertigo alpestris Alder, 1838",
    note: "",
  },
  {
    speciesName: "Vertigo angustior",
    abbreviation: "VerAng",
    group: "Terrestrial",
    speciesAndAuthor: "Vertigo angustior Jeffreys, 1830",
    note: "Specialist",
  },
  {
    speciesName: "Vertigo antivertigo",
    abbreviation: "VerAnt",
    group: "Terrestrial",
    speciesAndAuthor: "Vertigo antivertigo (Draparnaud, 1801)",
    note: "Specialist",
  },
  {
    speciesName: "Vertigo arctica",
    abbreviation: "VerArc",
    group: "Terrestrial",
    speciesAndAuthor: "Vertigo arctica (Wallenberg, 1858)",
    note: "Relict",
  },
  {
    speciesName: "Vertigo genesii",
    abbreviation: "VerGen",
    group: "Terrestrial",
    speciesAndAuthor: "Vertigo genesii (Gredler, 1856)",
    note: "Relict",
  },
  {
    speciesName: "Vertigo geyeri",
    abbreviation: "VerGey",
    group: "Terrestrial",
    speciesAndAuthor: "Vertigo geyeri Lindholm, 1925",
    note: "Relict",
  },
  {
    speciesName: "Vertigo lilljeborgi",
    abbreviation: "VerLil",
    group: "Terrestrial",
    speciesAndAuthor: "Vertigo lilljeborgi (Westerlund, 1871)",
    note: "Relict",
  },
  {
    speciesName: "Vertigo moulinsiana",
    abbreviation: "VerMou",
    group: "Terrestrial",
    speciesAndAuthor: "Vertigo moulinsiana (Dupuy, 1849)",
    note: "Specialist",
  },
  {
    speciesName: "Vertigo pusilla",
    abbreviation: "VerPus",
    group: "Terrestrial",
    speciesAndAuthor: "Vertigo pusilla O. F. Müller, 1774",
    note: "",
  },
  {
    speciesName: "Vertigo pygmaea",
    abbreviation: "VerPyg",
    group: "Terrestrial",
    speciesAndAuthor: "Vertigo pygmaea (Draparnaud, 1801)",
    note: "",
  },
  {
    speciesName: "Vertigo ronnebyensis",
    abbreviation: "VerRon",
    group: "Terrestrial",
    speciesAndAuthor: "Vertigo ronnebyensis (Westerlund, 1871)",
    note: "",
  },
  {
    speciesName: "Vertigo substriata",
    abbreviation: "VerSub",
    group: "Terrestrial",
    speciesAndAuthor: "Vertigo substriata (Jeffreys, 1833)",
    note: "",
  },
  {
    speciesName: "Vestia elata",
    abbreviation: "VesEla",
    group: "Terrestrial",
    speciesAndAuthor: "Vestia elata (Rossmässler, 1836)",
    note: "",
  },
  {
    speciesName: "Vestia gulo",
    abbreviation: "VesGul",
    group: "Terrestrial",
    speciesAndAuthor: "Vestia gulo (E. A. Bielz, 1859)",
    note: "",
  },
  {
    speciesName: "Vestia ranojevici",
    abbreviation: "VesRan",
    group: "Terrestrial",
    speciesAndAuthor: "Vestia ranojevici moravica (Brabenec, 1952)",
    note: "",
  },
  {
    speciesName: "Vestia turgida",
    abbreviation: "VesTur",
    group: "Terrestrial",
    speciesAndAuthor: "Vestia turgida (Rossmässler, 1836)",
    note: "",
  },
  {
    speciesName: "Vitrea contracta",
    abbreviation: "VitCon",
    group: "Terrestrial",
    speciesAndAuthor: "Vitrea contracta (Westerlund, 1871)",
    note: "",
  },
  {
    speciesName: "Vitrea crystallina",
    abbreviation: "VitCry",
    group: "Terrestrial",
    speciesAndAuthor: "Vitrea crystallina (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Vitrea diaphana",
    abbreviation: "VitDia",
    group: "Terrestrial",
    speciesAndAuthor: "Vitrea diaphana (Studer, 1820)",
    note: "",
  },
  {
    speciesName: "Vitrea subrimata",
    abbreviation: "VitSub",
    group: "Terrestrial",
    speciesAndAuthor: "Vitrea subrimata (Reinhardt, 1871)",
    note: "",
  },
  {
    speciesName: "Vitrea transsylvanica",
    abbreviation: "VitTra",
    group: "Terrestrial",
    speciesAndAuthor: "Vitrea transsylvanica (Clessin, 1877)",
    note: "",
  },
  {
    speciesName: "Vitrina pellucida",
    abbreviation: "VitPel",
    group: "Terrestrial",
    speciesAndAuthor: "Vitrina pellucida (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Vitrinobrachium breve",
    abbreviation: "VitBre",
    group: "Terrestrial",
    speciesAndAuthor: "Vitrinobrachium breve (Férussac, 1821)",
    note: "",
  },
  {
    speciesName: "Viviparus acerosus",
    abbreviation: "VivAce",
    group: "Aquatic",
    speciesAndAuthor: "Viviparus acerosus Bourguignat, 1862",
    note: "",
  },
  {
    speciesName: "Viviparus contectus",
    abbreviation: "VivCon",
    group: "Aquatic",
    speciesAndAuthor: "Viviparus contectus (Millet, 1813)",
    note: "",
  },
  {
    speciesName: "Viviparus viviparus",
    abbreviation: "VivViv",
    group: "Aquatic",
    speciesAndAuthor: "Viviparus viviparus (Linné, 1758)",
    note: "",
  },
  {
    speciesName: "Xerolenta obvia",
    abbreviation: "XerObv",
    group: "Terrestrial",
    speciesAndAuthor: "Xerolenta obvia (Menke, 1828)",
    note: "",
  },
  {
    speciesName: "Zebrina detrita",
    abbreviation: "ZebDet",
    group: "Terrestrial",
    speciesAndAuthor: "Zebrina detrita (O. F. Müller, 1774)",
    note: "",
  },
  {
    speciesName: "Zonitoides arboreus",
    abbreviation: "ZonArb",
    group: "Terrestrial",
    speciesAndAuthor: "Zonitoides arboreus (Say, 1817)",
    note: "",
  },
  {
    speciesName: "Zonitoides nitidus",
    abbreviation: "ZonNit",
    group: "Terrestrial",
    speciesAndAuthor: "Zonitoides nitidus (O. F. Müller, 1774)",
    note: "",
  },
];
